---
apiVersion: v1
kind: pod
metadata:
  name: prash
  labels:
    app: jenkins
    spec:
      containers:
        - image: nginx
        name: prashanth
        ports:
          - containerPort: 8080
          protocol: TCP