apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: nginx
  name: prashanth
spec:
  minReadySeconds: 15
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:  
    metadata:
      labels:
        app: nginx
      name: prash1
    spec:
      containers:
        - image: jenkins/jenkins
          name: prashu
          ports:
            - containerPort: 8080
              protocol: TCP    