apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: nginx
  name: prashanth
spec:
  minReadySeconds: 15sec
  replicas: 5
  selector:
    app: nginx
  template:  
    metadata:
      labels:
        app: nginx
      name: prash
    spec:
      containers:
        - image: nginx
          name: prash1
          ports:
            - containerPort: 80
              protocol: TCP    