apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: nginx
  name: prashanth
spec:
  minReadySeconds: 15
  replicas: 5
  selector:
    app: nginx
  template:  
    metadata:
      labels:
        app: nginx
      name: prash1
    spec:
      containers:
        - image: jenkins
          name: prashu
          ports:
            - containerPort: 8080
              protocol: TCP    